image: golang:latest

stages:
    - build
    - test

variables:
  DOCKER_IMAGE_TAGGED: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA 
  DOCKER_IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest 

build_image:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_TAGGED target/docker/stage/
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $DOCKER_IMAGE_TAGGED
  tags:
    - run.consolving.net 

test-access:
  stage: test
  script:
    - echo $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
    - scripts/get.sh
  tags:
    - run.consolving.net 
