image: phaus/docker-golang-build:1.11-alpine

stages:
  - build
  - test
  - publish

variables:
  DOCKER_IMAGE_TAGGED: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA 
  DOCKER_IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest 
  REPO_NAME: git-lab.de/$CI_PROJECT_PATH

build_image:
  stage: build
  image: docker:latest
  script:
    - docker build -t $DOCKER_IMAGE_TAGGED .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $DOCKER_IMAGE_TAGGED
  tags:
    - run.consolving.net

test_image:
  stage: test
  image: $DOCKER_IMAGE_TAGGED
  script:
    - cleaner
    - cleaner test
  tags:
    - run.consolving.net  