image: golang:latest

stages:
    - test

test-access:
  stage: test
  script:
    - echo $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
    - curl $CI_PROJECT_URL/registry/repository/$CI_PROJECT_ID/tags?format=json
    - scripts/get.sh
  tags:
    - run.consolving.net 
