image: phaus/docker-golang-build:1.11-alpine

stages:
  - build
  - test
  - publish

build_image:
  stage: build
  image: docker:latest
  script:
    - docker build --pull -t "${CI_REGISTRY_IMAGE}" -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push "${CI_REGISTRY_IMAGE}"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
  tags:
    - run.consolving.net

test_image:
  stage: test
  image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
  script:
    - cleaner
    - cleaner test
    - cleaner list
  tags:
    - run.consolving.net
