image: golang:latest

stages:
    - test

test-access:
  stage: test
  script:
    - echo $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
    - echo $CI_REGISTRY/repository/$CI_PROJECT_ID/tags?format=json
    - curl $CI_REGISTRY -u gitlab-ci-token:$CI_JOB_TOKEN -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' 
